## Importing Libraries

In [2]:
%pip install tensorflow matplotlib pandas seaborn

import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

Note: you may need to restart the kernel to use updated packages.


## Data Preprocessing

### Training Image Preprocessing

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [6]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [7]:
for x,y in training_set:
  print(x, x.shape)
  print(y, y.shape)
  break

tf.Tensor(
[[[[ 93.5   85.5   83.75]
   [184.5  176.5  173.5 ]
   [178.75 170.75 167.75]
   ...
   [193.   187.   189.  ]
   [194.   188.   190.  ]
   [197.   191.   193.  ]]

  [[ 93.5   86.25  84.75]
   [191.75 183.75 180.75]
   [180.   172.   169.  ]
   ...
   [189.75 183.75 185.75]
   [190.   184.   186.  ]
   [193.   187.   189.  ]]

  [[ 92.25  84.75  83.  ]
   [184.5  176.5  173.5 ]
   [181.5  173.5  170.5 ]
   ...
   [191.25 185.25 187.25]
   [191.   185.   187.  ]
   [192.75 186.75 188.75]]

  ...

  [[ 91.25  82.75  81.75]
   [174.5  164.5  162.5 ]
   [176.   166.   164.  ]
   ...
   [185.5  179.5  181.5 ]
   [189.   183.   185.  ]
   [196.25 190.25 192.25]]

  [[ 90.75  82.25  81.25]
   [173.75 163.75 161.75]
   [173.5  163.5  161.5 ]
   ...
   [195.25 189.25 191.25]
   [186.   180.   182.  ]
   [199.   193.   195.  ]]

  [[ 89.25  80.75  79.75]
   [167.75 157.75 155.75]
   [171.   161.   159.  ]
   ...
   [196.   190.   192.  ]
   [194.75 188.75 190.75]
   [198.   192.   19